feat(buses): 大幅改寫 buses 接口的底層實作、修改 buses 接口
NTHU-SA/NTHU-Data-API pull request #51
Opened 2023-12-16 10:29 UTC by iwtba4188

- 使用 pandas DataFrame 管理多維資料
- 改寫成這樣貌似有讓沒快取的時候執行時間變長，但有快取時還是很快，之後找時間重構提高性能
- 原本重複性高的接口改用更 general 的寫法

2023-12-16 11:08 UTC, l7wei requested changes
```python
from datetime import datetime
current_ = datetime.now()
current_time = current.time().strftime("%H:%M")
current_day = current_.now().weekday()
```
可以加入一個獲取當前時間公車班次的方法

2023-12-16 11:21 UTC, l7wei requested changes
大抵上沒問題，剩下一些 smell ！解決之後就 merge 囉

2023-12-16 11:21 UTC, l7wei commented on src/api/models/buses.py
> +        self.stoped_bus = pd.DataFrame(data={"data": [[] * 18]}, index=schedule_index)
可以新增註釋，直覺上不太好理解為什麼是 *18

2023-12-16 11:21 UTC, l7wei commented on src/api/models/buses.py
> +        print(variable_string)
print() 要移除，或是用
```python
from loguru import logger
logger.debug(string)
```
處理，不然 SERVER 端會出現無用 LOG，或是被視為錯誤

2023-12-16 11:21 UTC, l7wei commented on src/api/models/buses.py
> +        print(variable_string)
print 要移除

2023-12-16 11:21 UTC, l7wei commented on src/api/models/buses.py
> +        for scope in ["main", "nanda"]:
新增註釋解釋為什麼是 main/nanda -> route -> day 這樣的迴圈

2023-12-16 11:22 UTC, l7wei commented
使用 pandas DataFrame 是個好辦法！辛苦了 ><

2023-12-16 11:53 UTC, iwtba4188 commented on src/api/models/buses.py
> +        self.stoped_bus = pd.DataFrame(data={"data": [[] * 18]}, index=schedule_index)
已補，轉一份在這：
> self.stoped_bus 共有 18 個 entries 需要被初始賦值為空 list，避免後續對 nan 做 append() 導致錯誤

2023-12-16 11:53 UTC, iwtba4188 commented on src/api/models/buses.py
> +        print(variable_string)
debug 遺跡，移掉了

2023-12-16 11:53 UTC, iwtba4188 commented on src/api/models/buses.py
> +        print(variable_string)
debug 遺跡，移掉了

2023-12-16 11:54 UTC, iwtba4188 commented on src/api/models/buses.py
> +        for scope in ["main", "nanda"]:
這個不懂QQ 是要說明這是在遍歷所有可能的情況嗎？

2023-12-16 11:56 UTC, iwtba4188 commented
> ```python
> from datetime import datetime
> current = datetime.now()
> current_time = current.time().strftime("%H:%M")
> current_day = current.now().weekday()
> ```
> 
> 可以加入一個獲取當前時間公車班次的方法

你看一下我後面推的那些 current 端口是不是跟你想的一樣

2023-12-16 15:20 UTC, l7wei commented on src/api/models/buses.py
> +        for scope in ["main", "nanda"]:
YES, 還有解釋為什麼這樣設計階層。

2023-12-16 15:28 UTC, l7wei commented
> > ```python
> > from datetime import datetime
> > current = datetime.now()
> > current_time = current.time().strftime("%H:%M")
> > current_day = current.now().weekday()
> > ```
> > 
> > 可以加入一個獲取當前時間公車班次的方法
> 
> 你看一下我後面推的那些 current 端口是不是跟你想的一樣
> 
> btw, 今天沒公車所以我也不知道我寫的對不對
> 然後理論上沒找到要 404，但我還沒弄：D 先讓他 200

endpoint 用 /stops/.../current 會更一些（這個站點有一個 current 物件可以存取）

剛剛注意到，你都用 def 而不用 async def，為什麼呀 ><

2023-12-16 15:37 UTC, iwtba4188 commented on src/api/models/buses.py
> +        for scope in ["main", "nanda"]:
這一段我覺得足夠直觀應該不需要說明他在做什麼吧(?) 而且老實說順序其實沒有和前端的變數名稱的順序一樣，還是你有其他的考量？

2023-12-16 15:40 UTC, iwtba4188 commented
> > > ```python
> > > from datetime import datetime
> > > current = datetime.now()
> > > current_time = current.time().strftime("%H:%M")
> > > current_day = current.now().weekday()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以加入一個獲取當前時間公車班次的方法
> > 
> > 
> > 你看一下我後面推的那些 current 端口是不是跟你想的一樣
> > btw, 今天沒公車所以我也不知道我寫的對不對
> > 然後理論上沒找到要 404，但我還沒弄：D 先讓他 200
> 
> endpoint 用 /stops/.../current 會更一些（這個站點有一個 current 物件可以存取）
> 
> [Reference](https://stackoverflow.com/questions/42387494/is-it-legal-to-have-rest-resource-such-as-currentuser-in-terms-of-restful-and-s)
> 
> 另外剛剛注意到，你都用 def 而不用 async def，為什麼呀 ><

因為函式裡面沒有要 await 的部分，理論上應該不需要加上 async 關鍵字，印象中 fastapi 好像是用其他方法做異步的，還是我記錯ㄌ？

2023-12-16 16:11 UTC, l7wei commented
> > > > ```python
> > > > from datetime import datetime
> > > > current = datetime.now()
> > > > current_time = current.time().strftime("%H:%M")
> > > > current_day = current.now().weekday()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 可以加入一個獲取當前時間公車班次的方法
> > > 
> > > 
> > > 你看一下我後面推的那些 current 端口是不是跟你想的一樣
> > > btw, 今天沒公車所以我也不知道我寫的對不對
> > > 然後理論上沒找到要 404，但我還沒弄：D 先讓他 200
> > 
> > endpoint 用 /stops/.../current 會更一些（這個站點有一個 current 物件可以存取）
> > 
> > [Reference](https://stackoverflow.com/questions/42387494/is-it-legal-to-have-rest-resource-such-as-currentuser-in-terms-of-restful-and-s)
> > 
> > 另外剛剛注意到，你都用 def 而不用 async def，為什麼呀 ><
> 
> endpoints 那裡要放到 day 那裡還是去掉 day 把 current 加到最後面？
> `/stops/{stop_name}/{bus_type}/current/{direction}` or `/stops/{stop_name}/{bus_type}/{direction}/current`
> 
> 因為函式裡面沒有要 await 的部分，理論上應該不需要加上 async 關鍵字，印象中 fastapi 好像是用其他方法做異步的，還是我記錯ㄌ？

沒記錯的話，async def 比較不會被 Python’s GIL (global interpreter lock) Block.

Reference:

[The difference between def and async def in FastAPI](https://ysk24ok.github.io/2021/09/02/difference_between_def_and_async_def_in_fastapi.html)

2023-12-17 14:29 UTC, iwtba4188 commented
- 目前 stopped 端口還有問題，已經知道是 list ref 的問題：
  ```python
  class Stop:
      def __init__(self, name, name_en) -> None:
          self.name = name
          self.name_en = name_en
          # self.stopped_bus 共有 18 個 entries 需要被初始賦值為空 list，避免後續對 nan 做 append() 導致錯誤
          self.stopped_bus = pd.DataFrame(data={"data": [[] * 18]}, index=schedule_index)
  ```
  其中，`data={"data": [[] * 18]}` 是淺複製，改其中一個會影響到另外 18 個，我找超久才發現= =
- tests 待修、待補

2023-12-17 14:32 UTC, iwtba4188 commented on src/api/models/buses.py
> +        for scope in ["main", "nanda"]:
這我懂了，對我來講太直觀（因為是我寫的），結果沒發現其實順序有差，這裡轉一份：
> 務必保持之後的程式碼中，BUS_TYPE、BUS_DAY、BUS_DIRECTION 的順序一致，因為 BusType、BusDay 具有 all 這個選項，之後合併要先處理完 BusDirection 的部份才會合併到 all

2023-12-17 14:34 UTC, iwtba4188 commented
> > > > > ```python
> > > > > from datetime import datetime
> > > > > current = datetime.now()
> > > > > current_time = current.time().strftime("%H:%M")
> > > > > current_day = current.now().weekday()
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 可以加入一個獲取當前時間公車班次的方法
> > > > 
> > > > 
> > > > 你看一下我後面推的那些 current 端口是不是跟你想的一樣
> > > > btw, 今天沒公車所以我也不知道我寫的對不對
> > > > 然後理論上沒找到要 404，但我還沒弄：D 先讓他 200
> > > 
> > > 
> > > endpoint 用 /stops/.../current 會更一些（這個站點有一個 current 物件可以存取）
> > > [Reference](https://stackoverflow.com/questions/42387494/is-it-legal-to-have-rest-resource-such-as-currentuser-in-terms-of-restful-and-s)
> > > 另外剛剛注意到，你都用 def 而不用 async def，為什麼呀 ><
> > 
> > 
> > endpoints 那裡要放到 day 那裡還是去掉 day 把 current 加到最後面？
> > `/stops/{stop_name}/{bus_type}/current/{direction}` or `/stops/{stop_name}/{bus_type}/{direction}/current`
> > 因為函式裡面沒有要 await 的部分，理論上應該不需要加上 async 關鍵字，印象中 fastapi 好像是用其他方法做異步的，還是我記錯ㄌ？
> 
> 沒記錯的話，async def 比較不會被 Python’s GIL (global interpreter lock) Block.
> 
> Reference: [The difference between def and async def in FastAPI](https://ysk24ok.github.io/2021/09/02/difference_between_def_and_async_def_in_fastapi.html)
> 
> 可以用 /stops/{stop_name}/{bus_type}/{direction}/current
> 
> 然後也改一下本來的路徑變成 /{day} 結尾會比較直觀（我猜目前還沒有 production 的環境用我們的資料？要不要直接一口氣改用 query parameters）
> 
> `/stops/{stop_name}`
> 
> `/stops/{stop_name}?bus_type={bus_type}&direction={direction}&day={day}`.

轉 DC 的紀錄以後比較好找：
> 主要用 `async def` 是要避免 CPU contention 的問題，但目前機器應該還可以承受調用的壓力不太會出現，[這篇](https://wuyiru.medium.com/python-%E6%B7%BA%E8%AB%87fastapi-async-def%E8%88%87def-e3a2a793af03) 是講實際的性能比對，[這篇](https://stackoverflow.com/questions/74229072/fastapi-with-uvicorn-wont-allow-thread-usage-to-exceed-65) 是講有人遇到 CPU contention 的問題有人提供都加上 `async` 的解法，我個人是比較傾向用 `def` 比較符合 `async` 這個關鍵字的語意也考量普遍情況的效能需求

2023-12-17 15:20 UTC, l7wei approved these changes

2023-12-17 15:21 UTC, merged

2023-12-17 15:22 UTC, l7wei commented
TODO: Buses tests